### ISSUE TITLE
can you compile it?

### ISSUE THREAD

**Issue by elapt1c** [GameHerobrine/MCCheat#1]
does it work on beta 1.1_02 and also do u have the original? i can archive it

**Comment by GameHerobrine** [comment]
> does it work on beta 1.1_02

the mccheat from here works only on a1.2.6 or b1.7.3.

> do u have the original

the original was found inside https://archive.org/details/HackedClients.7z but it looks like it is not available anymore
i also have [MCCheat.zip](https://github.com/user-attachments/files/15506643/MCCheat.zip) but not sure does it contain original unmodified mccheat or not

**Comment by GameHerobrine** [comment]
> can you compile it

you can
